name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Cache Buildozer
        uses: actions/cache@v4
        with:
          path: |
            ~/.buildozer
            ~/.android
          key: buildozer-${{ hashFiles('buildozer.spec') }}

      - name: Build APK using Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          command: yes | buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: faceapp-debug-apk
          path: bin/*.apk
